/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface SocketOptions {
  recvTimeout?: number
  sendTimeout?: number
}
export declare function lz4Compress(input: Buffer): Buffer
export class Socket {
  options: SocketOptions
  constructor(options?: SocketOptions | undefined | null)
  connect(url: string): void
  send(req: Buffer): Buffer
  close(): void
  connected(): boolean
  static testConnection(url: string, options?: SocketOptions | undefined | null): boolean
  static recvMessage(url: string, callback: (err: null | Error, bytes: Buffer) => void, options?: SocketOptions | undefined | null): MessageRecvDisposable
}
export class MessageRecvDisposable {
  dispose(): void
  isClosed(): boolean
  isConnectionAlive(): boolean
}
