/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export const enum ProtocolType {
  Pair0 = 0,
  Pair1 = 1,
  Pub0 = 2,
  Sub0 = 3,
  Req0 = 4,
  Rep0 = 5,
  Surveyor0 = 6,
  Push0 = 7,
  Pull0 = 8,
  Bus0 = 9
}
export class SocketWrapper {
  constructor()
  connect(protocol: ProtocolType, url: string): void
  send(message: Buffer): Buffer
  recv(callback: (err: Error | null, arg: Buffer) => any): void
  close(): void
  isConnect(): boolean
}
